PINECONE_API_KEY="pcsk_3VGwGk_AdeQhYH5nG5McXF3PZoGaweBJTEhFYYoGkisN8Y7CnWjyWJZvLLvSBgVr3nshEk"
PINECONE_ENV="us-east-1-aws"
PINECONE_INDEX_NAME="tarottara-index"
PINECONE_REGION="us-east-1"
PINECONE_CLOUD="aws"

ASSEMBLYAI_API_KEY="d39bc664c0384303aa4ebea5733daf30"
ELEVENLABS_API_KEY="sk_9051a60f00853379ed9071ccc0fd4b232b7ce9007a3e1dfd"
GROQ_API_KEY="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"

